# Generated by Django 3.1.2 on 2020-10-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('name', models.CharField(help_text='Provider name', max_length=50)),
                ('desc', models.TextField(help_text='Provider description')),
                ('specialty', models.TextField(help_text='Provider specialties')),
                ('image_sml', models.URLField()),
                ('image_med', models.URLField()),
                ('image_lrg', models.URLField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ed_type', models.IntegerField(choices=[(1, 'College'), (2, 'Advanced Degree'), (3, 'Medical School'), (4, 'Internship'), (5, 'Residency')], default=1)),
                ('school_name', models.CharField(max_length=50)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='CertOrgRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certOrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.certorg')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
        ),
        migrations.AddField(
            model_name='certorg',
            name='members',
            field=models.ManyToManyField(through='providers.CertOrgRelationship', to='providers.Provider'),
        ),
    ]
