# Generated by Django 3.1.2 on 2020-10-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_youtubevid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['view_order']},
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='order',
            new_name='view_order',
        ),
    ]
