# Generated by Django 3.1.2 on 2020-10-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_auto_20201027_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='desc',
        ),
        migrations.AddField(
            model_name='provider',
            name='bio',
            field=models.TextField(default='', help_text='Bio'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(help_text='Full name with creds', max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='specialty',
            field=models.TextField(help_text='Specialties'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='view_order',
            field=models.IntegerField(default=1, help_text='The display order of this provider'),
        ),
    ]
