# Generated by Django 3.1.2 on 2020-10-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_auto_20201027_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='key',
            field=models.CharField(default='', help_text='url_slug', max_length=25),
        ),
    ]
