# Generated by Django 3.1.2 on 2020-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_provider_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='key',
            field=models.CharField(default='', help_text='URL Path Slug', max_length=25),
        ),
    ]
