# Generated by Django 3.1.2 on 2020-10-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_auto_20201028_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='key',
            new_name='slug',
        ),
    ]
