# Generated by Django 3.1.2 on 2020-10-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_auto_20201028_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolrelationship',
            name='degree',
            field=models.TextField(blank=True, default='', help_text='Degree (Optional)'),
        ),
    ]
