# Generated by Django 3.1.2 on 2020-11-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_auto_20201030_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='image_lrg',
        ),
        migrations.AddField(
            model_name='provider',
            name='image_large',
            field=models.FileField(default='', help_text='Large provider image', upload_to='static/images/providers'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='image_med',
            field=models.FileField(default='', help_text='Medium provider image', upload_to='static/images/providers'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='image_sml',
            field=models.FileField(default='', help_text='Small provider image', upload_to='static/images/providers'),
        ),
    ]
