# Generated by Django 3.1.2 on 2020-11-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0012_auto_20201109_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='image_large',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='image_med',
        ),
    ]
