# Generated by Django 3.1.2 on 2020-12-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_auto_20201109_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolrelationship',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
