# Generated by Django 3.1.2 on 2020-12-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0014_schoolrelationship_graduation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Bio'),
        ),
    ]
