# Generated by Django 3.1.2 on 2020-12-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', help_text='URL Path Slug', max_length=25)),
                ('view_order', models.IntegerField(default=1, help_text='The display order of this service')),
                ('name', models.CharField(default='', help_text='Service name', max_length=50)),
                ('icon', models.FileField(default='', help_text='Icon image for service', upload_to='static/images/icons')),
                ('summary_desc', models.TextField(default='', help_text='Description for the main Services page (can be html)')),
                ('desc', models.TextField(default='', help_text='Description (can be html)')),
                ('services', models.TextField(help_text='Services (can be html)')),
                ('sidebar', models.TextField(help_text='Sidebar (can be html)')),
            ],
            options={
                'ordering': ['view_order'],
            },
        ),
    ]
