# Generated by Django 3.1.2 on 2020-10-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.CharField(default='', help_text='URL Path Slug', max_length=25),
        ),
    ]
