# Generated by Django 3.1.2 on 2020-11-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.URLField(default='', help_text='Icon image for service'),
        ),
    ]
