# Generated by Django 3.1.2 on 2020-11-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(default='', help_text='Icon image for service', upload_to=None),
        ),
    ]
