# Generated by Django 3.1.2 on 2020-11-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20201109_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(default='', help_text='Icon image for service', upload_to='static/images/SVGs'),
        ),
    ]
