# Generated by Django 3.1.2 on 2020-11-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20201109_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(default='', help_text='Icon image for service', upload_to='static/images/icons'),
        ),
    ]
