# Generated by Django 3.1.2 on 2020-11-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20201113_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='summary_desc',
            field=models.TextField(default='', help_text='Description for the main Services page (can be html)'),
        ),
    ]
