# Generated by Django 3.1.2 on 2020-11-24 02:19

from django.db import migrations, models
import header.models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='expiration_date',
            field=models.DateTimeField(default=header.models.Banner.one_year_from_today, help_text='When should this banner stop being displayed? (Defaults 1 year from now)'),
        ),
    ]
