# Generated by Django 3.1.2 on 2020-12-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', help_text='URL Path Slug', max_length=25)),
                ('view_order', models.IntegerField(default=1, help_text='The display order of this FAQ')),
                ('question', models.TextField(help_text='Frequently asked Question')),
                ('answer', models.TextField(help_text='FAQ Response (html)')),
                ('special', models.TextField(help_text='FAQ Response special area (html)')),
                ('faq_type', models.IntegerField(choices=[(1, 'Obstetric'), (2, 'Gynecology'), (3, 'Postoperative')], default=1)),
            ],
            options={
                'ordering': ['view_order'],
            },
        ),
    ]
