# Generated by Django 3.1.2 on 2020-12-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['faq_type', 'view_order']},
        ),
        migrations.AlterField(
            model_name='faq',
            name='faq_type',
            field=models.IntegerField(choices=[(1, 'Obstetrics'), (2, 'Gynecology'), (3, 'Postoperative')], default=1),
        ),
    ]
