# Generated by Django 3.1.2 on 2020-12-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_auto_20201223_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=models.CharField(default='', help_text='URL Path Slug', max_length=50),
        ),
    ]
