# Generated by Django 3.1.2 on 2020-12-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_auto_20201223_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='special',
            field=models.TextField(blank=True, help_text='FAQ Response special area (html)', null=True),
        ),
    ]
