# Generated by Django 3.1.2 on 2020-12-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0004_auto_20201223_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='old_path',
            field=models.CharField(blank=True, default='', help_text='If moved from old site, this is the old faq id (eg "ob_q5")', max_length=50),
        ),
    ]
