# Generated by Django 3.1.2 on 2020-11-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='isPrimary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='highlighted_content',
            field=models.TextField(blank=True, default='', help_text='Special content to highlight (can be html)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='', help_text='Name', max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent_facility',
            field=models.CharField(blank=True, default='', help_text='The name of the parent facility (eg "Liberty Hospital")', max_length=40),
        ),
    ]
