# Generated by Django 3.1.2 on 2020-12-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20201112_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='address1',
            field=models.TextField(default='', help_text='Address1'),
        ),
        migrations.AddField(
            model_name='location',
            name='address2',
            field=models.TextField(blank=True, default='', help_text='Address2'),
        ),
        migrations.AddField(
            model_name='location',
            name='city_state_zip',
            field=models.TextField(default='', help_text='City, State Zip'),
        ),
    ]
