# Generated by Django 3.1.2 on 2020-12-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_order', models.IntegerField(default=1, help_text='The display order of this FAQ link')),
                ('name', models.CharField(default='', help_text='FAQ Link name', max_length=50)),
                ('file', models.FileField(blank=True, default='', upload_to='faq/')),
                ('file_type', models.CharField(blank=True, default='', max_length=4)),
                ('link', models.URLField(blank=True, default='', help_text='Link (optional)')),
            ],
            options={
                'ordering': ['view_order'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_order', models.IntegerField(default=1, help_text='The display order of this form')),
                ('name', models.CharField(default='', help_text='Form name', max_length=50)),
                ('file', models.FileField(blank=True, default='', upload_to='forms/')),
                ('file_type', models.CharField(blank=True, default='', max_length=4)),
                ('link', models.URLField(blank=True, default='', help_text='Link (optional)')),
            ],
            options={
                'ordering': ['view_order'],
            },
        ),
        migrations.CreateModel(
            name='HealthPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Health Plan name', max_length=200)),
                ('link', models.URLField(blank=True, default='', help_text='Link (optional)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_order', models.IntegerField(default=1, help_text='The display order of this information link')),
                ('name', models.CharField(default='', help_text='Link name', max_length=50)),
                ('file', models.FileField(blank=True, default='', upload_to='info/')),
                ('file_type', models.CharField(blank=True, default='', max_length=4)),
                ('link', models.URLField(blank=True, default='', help_text='Link (optional)')),
            ],
            options={
                'ordering': ['view_order'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', help_text='URL Path Slug', max_length=25)),
                ('view_order', models.IntegerField(default=1, help_text='The display order of this resource')),
                ('name', models.CharField(default='', help_text='Resource name', max_length=50)),
                ('icon', models.FileField(default='', help_text='Icon image for resource', upload_to='static/images/icons')),
                ('isLink', models.BooleanField(default=False, help_text='Is this menu item an external link?')),
                ('isFormLink', models.BooleanField(default=False, help_text='Is this menu item a form submittal?')),
                ('external_link', models.URLField(blank=True, default='', help_text='External link (optional)')),
                ('content', models.TextField(blank=True, default='', help_text='Page content (only if not a link)')),
                ('form_content', models.TextField(blank=True, default='', help_text='The raw form html')),
            ],
            options={
                'ordering': ['view_order'],
            },
        ),
    ]
