# Generated by Django 3.1.2 on 2020-12-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqlink',
            name='link',
            field=models.CharField(blank=True, default='', help_text='Relative link (optional. ex /faqs/obstetrics)', max_length=200),
        ),
    ]
