# Generated by Django 3.1.2 on 2020-11-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['view_order']},
        ),
        migrations.AddField(
            model_name='resource',
            name='desc',
            field=models.TextField(default='', help_text='Description (can be html)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='icon',
            field=models.FileField(default='', help_text='Icon image for resource', upload_to='static/images/icons'),
        ),
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(default='', help_text='Resource name', max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.CharField(default='', help_text='URL Path Slug', max_length=25),
        ),
        migrations.AddField(
            model_name='resource',
            name='view_order',
            field=models.IntegerField(default=1, help_text='The display order of this resource'),
        ),
    ]
