# Generated by Django 3.1.2 on 2020-11-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20201113_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='desc',
        ),
    ]
