# Generated by Django 3.1.2 on 2020-12-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20201231_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='link',
            field=models.CharField(blank=True, default='', help_text='Relative Link (optional)', max_length=200),
        ),
    ]
