# Generated by Django 3.1.2 on 2020-12-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20201231_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqlink',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='form',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='forms'),
        ),
        migrations.AlterField(
            model_name='info',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='info'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='icon',
            field=models.FileField(default='', help_text='Icon image for resource', upload_to='icons'),
        ),
    ]
