# Generated by Django 3.1.2 on 2020-11-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_resource_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Page content (only if not a link)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='external_link',
            field=models.URLField(blank=True, default='', help_text='External link (optional)'),
        ),
        migrations.AddField(
            model_name='resource',
            name='isLink',
            field=models.BooleanField(default=False, help_text='Is this menu item an external link?'),
        ),
    ]
