# Generated by Django 3.1.2 on 2020-11-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20201118_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='form_content',
            field=models.TextField(blank=True, default='', help_text='The raw form html'),
        ),
        migrations.AddField(
            model_name='resource',
            name='isFormLink',
            field=models.BooleanField(default=False, help_text='Is this menu item a form submittal?'),
        ),
    ]
