# Generated by Django 3.1.2 on 2020-12-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20201118_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_order', models.IntegerField(default=1, help_text='The display order of this FAQ link')),
                ('name', models.CharField(default='', help_text='FAQ Link name', max_length=50)),
                ('file', models.FileField(blank=True, default='', upload_to='faq/')),
                ('link', models.URLField(blank=True, default='', help_text='Link (optional)')),
            ],
            options={
                'ordering': ['view_order'],
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_order', models.IntegerField(default=1, help_text='The display order of this form')),
                ('name', models.CharField(default='', help_text='Form name', max_length=50)),
                ('file', models.FileField(blank=True, default='', upload_to='forms/')),
                ('link', models.URLField(blank=True, default='', help_text='Link (optional)')),
            ],
            options={
                'ordering': ['view_order'],
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_order', models.IntegerField(default=1, help_text='The display order of this information link')),
                ('name', models.CharField(default='', help_text='Link name', max_length=50)),
                ('file', models.FileField(blank=True, default='', upload_to='info/')),
                ('link', models.URLField(blank=True, default='', help_text='Link (optional)')),
            ],
            options={
                'ordering': ['view_order'],
            },
        ),
    ]
