# Generated by Django 3.1.2 on 2020-12-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_faqs_forms_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQs',
            new_name='FAQ',
        ),
    ]
