# Generated by Django 3.1.2 on 2020-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20201213_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='file_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='form',
            name='file_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='file_type',
            field=models.TextField(blank=True, default=''),
        ),
    ]
