# Generated by Django 3.1.2 on 2020-12-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20201213_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='form',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='info',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
