# Generated by Django 3.1.2 on 2020-12-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_healthplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthplan',
            name='name',
            field=models.CharField(default='', help_text='Health Plan name', max_length=200),
        ),
    ]
